%% set data folder
cdslib = 'C:\Users\kpb8927\data\cds-library';


files = dir(fullfile(cdslib,'*CObumpmove_001*'));
names = vertcat({files.name})';

load_params = struct(...
    'array_name','S1',...
    'cds_array_name','LeftS1',...
    'cont_signal_names',{{...
        'pos',...
	    'vel',...
        'force',...
        }},...
    'event_names',{{...
        'startTime',...
        'endTime',...
        'goCueTime',...
        'bumpTime',...
        }},...
    'trial_meta',{{...
        'bumpDir',...
        'tgtDir',...
        'spaceNum',...
        }},...
     'extract_emg',false,...
     'extract_spikes',true,...
     'bin_size',0.01);

td_cell = cell(length(names),1);
for i = 1%:length(names)
    td_cell{i} = loadTDfromCDS(fullfile(cdslib,names{i}),load_params);
    fprintf('File %d processed\n',i)
end

%%
savedir = 'C:\Users\kpb8927\data\td-library';

file_info_cell = cell(length(names),6);

for i = 1%:length(names)
    file_info_cell(i,:) = strsplit(names{i},{'_','.'});
end

file_info = struct(...
    'monkey',file_info_cell(:,1),...
    'date',file_info_cell(:,2),...
    'filenum',file_info_cell(:,5));

% for i = [1,4:length(td_cell)]
for i = 1%:length(names)
    trial_data = td_cell{i};
%     trial_data = getRelMusLen(trial_data,[]);
%     trial_data = getNormEMG(trial_data,[]);
    
    save(fullfile(savedir,sprintf('%s_%s_CObumpmove_10ms.mat',file_info(i).monkey,file_info(i).date)),'trial_data','-v7.3')
    fprintf('File %d saved\n',i)
end

%%
% trial_data = horzcat(td_cell{2:3});
% save(fullfile(savedir,sprintf('%s_%s_COactpas_TD.mat',file_info(2).monkey,file_info(2).date)),'trial_data')